'use strict';

var DATA_EASY = {

/* ================================================================
   VERBS – 82 unregelmäßige Verben (A1/A2)
   ================================================================ */
VERBS: [
  { inf:"be",          past:"was/were",    de:"sein" },
  { inf:"beat",        past:"beat",        de:"schlagen" },
  { inf:"become",      past:"became",      de:"werden" },
  { inf:"begin",       past:"began",       de:"beginnen" },
  { inf:"bend",        past:"bent",        de:"biegen" },
  { inf:"bite",        past:"bit",         de:"beißen" },
  { inf:"blow",        past:"blew",        de:"blasen / wehen" },
  { inf:"break",       past:"broke",       de:"brechen" },
  { inf:"bring",       past:"brought",     de:"bringen" },
  { inf:"build",       past:"built",       de:"bauen" },
  { inf:"burn",        past:"burnt",       de:"brennen" },
  { inf:"buy",         past:"bought",      de:"kaufen" },
  { inf:"catch",       past:"caught",      de:"fangen" },
  { inf:"choose",      past:"chose",       de:"wählen / aussuchen" },
  { inf:"come",        past:"came",        de:"kommen" },
  { inf:"cost",        past:"cost",        de:"kosten" },
  { inf:"cut",         past:"cut",         de:"schneiden" },
  { inf:"do",          past:"did",         de:"machen / tun" },
  { inf:"draw",        past:"drew",        de:"zeichnen" },
  { inf:"drink",       past:"drank",       de:"trinken" },
  { inf:"drive",       past:"drove",       de:"fahren" },
  { inf:"eat",         past:"ate",         de:"essen" },
  { inf:"fall",        past:"fell",        de:"fallen" },
  { inf:"feel",        past:"felt",        de:"fühlen" },
  { inf:"fight",       past:"fought",      de:"kämpfen" },
  { inf:"find",        past:"found",       de:"finden" },
  { inf:"fly",         past:"flew",        de:"fliegen" },
  { inf:"forget",      past:"forgot",      de:"vergessen" },
  { inf:"get",         past:"got",         de:"bekommen / werden" },
  { inf:"give",        past:"gave",        de:"geben" },
  { inf:"go",          past:"went",        de:"gehen" },
  { inf:"grow",        past:"grew",        de:"wachsen / anbauen" },
  { inf:"have",        past:"had",         de:"haben" },
  { inf:"hear",        past:"heard",       de:"hören" },
  { inf:"hide",        past:"hid",         de:"verstecken" },
  { inf:"hit",         past:"hit",         de:"treffen / schlagen" },
  { inf:"hold",        past:"held",        de:"halten" },
  { inf:"hurt",        past:"hurt",        de:"verletzen / wehtun" },
  { inf:"keep",        past:"kept",        de:"behalten / halten" },
  { inf:"know",        past:"knew",        de:"wissen / kennen" },
  { inf:"lay",         past:"laid",        de:"legen (hinlegen)" },
  { inf:"lead",        past:"led",         de:"führen / leiten" },
  { inf:"leave",       past:"left",        de:"verlassen / gehen" },
  { inf:"lend",        past:"lent",        de:"verleihen / leihen" },
  { inf:"let",         past:"let",         de:"lassen / erlauben" },
  { inf:"lie",         past:"lay",         de:"liegen" },
  { inf:"lose",        past:"lost",        de:"verlieren" },
  { inf:"make",        past:"made",        de:"machen / herstellen" },
  { inf:"mean",        past:"meant",       de:"bedeuten / meinen" },
  { inf:"meet",        past:"met",         de:"treffen / kennenlernen" },
  { inf:"pay",         past:"paid",        de:"bezahlen" },
  { inf:"put",         past:"put",         de:"legen / stellen / setzen" },
  { inf:"read",        past:"read",        de:"lesen" },
  { inf:"ride",        past:"rode",        de:"reiten / fahren" },
  { inf:"ring",        past:"rang",        de:"klingeln / anrufen" },
  { inf:"rise",        past:"rose",        de:"aufsteigen / aufgehen" },
  { inf:"run",         past:"ran",         de:"laufen / rennen" },
  { inf:"say",         past:"said",        de:"sagen" },
  { inf:"see",         past:"saw",         de:"sehen" },
  { inf:"sell",        past:"sold",        de:"verkaufen" },
  { inf:"send",        past:"sent",        de:"schicken / senden" },
  { inf:"set",         past:"set",         de:"setzen / stellen / festlegen" },
  { inf:"shake",       past:"shook",       de:"schütteln" },
  { inf:"show",        past:"showed",      de:"zeigen" },
  { inf:"shut",        past:"shut",        de:"schließen" },
  { inf:"sing",        past:"sang",        de:"singen" },
  { inf:"sit",         past:"sat",         de:"sitzen" },
  { inf:"sleep",       past:"slept",       de:"schlafen" },
  { inf:"speak",       past:"spoke",       de:"sprechen" },
  { inf:"spend",       past:"spent",       de:"ausgeben / verbringen" },
  { inf:"stand",       past:"stood",       de:"stehen" },
  { inf:"steal",       past:"stole",       de:"stehlen" },
  { inf:"swim",        past:"swam",        de:"schwimmen" },
  { inf:"take",        past:"took",        de:"nehmen" },
  { inf:"teach",       past:"taught",      de:"lehren / unterrichten" },
  { inf:"tell",        past:"told",        de:"erzählen / sagen" },
  { inf:"think",       past:"thought",     de:"denken" },
  { inf:"throw",       past:"threw",       de:"werfen" },
  { inf:"understand",  past:"understood",  de:"verstehen" },
  { inf:"wake",        past:"woke",        de:"aufwachen / aufwecken" },
  { inf:"wear",        past:"wore",        de:"tragen (Kleidung)" },
  { inf:"win",         past:"won",         de:"gewinnen" },
  { inf:"write",       past:"wrote",       de:"schreiben" }
],

/* ================================================================
   SENTENCES – 50 Past-Simple-Sätze
   ================================================================ */
SENTENCES: [
  { words:["She","went","to","the","supermarket","yesterday."],          de:"Sie ging gestern in den Supermarkt." },
  { words:["He","ate","breakfast","at","seven","o'clock."],              de:"Er frühstückte um sieben Uhr." },
  { words:["They","played","football","in","the","park."],               de:"Sie spielten Fußball im Park." },
  { words:["I","watched","a","film","last","night."],                    de:"Ich sah letzte Nacht einen Film." },
  { words:["We","visited","our","grandparents","last","weekend."],       de:"Wir besuchten letztes Wochenende unsere Großeltern." },
  { words:["Tom","bought","a","new","bike","yesterday."],                de:"Tom kaufte gestern ein neues Fahrrad." },
  { words:["She","wrote","a","letter","to","her","friend."],             de:"Sie schrieb einen Brief an ihre Freundin." },
  { words:["The","children","ran","to","school."],                       de:"Die Kinder liefen zur Schule." },
  { words:["My","mother","cooked","dinner","at","home."],                de:"Meine Mutter kochte zu Hause Abendessen." },
  { words:["We","swam","in","the","lake","last","summer."],              de:"Wir schwammen letzten Sommer im See." },
  { words:["He","read","a","book","before","bed."],                      de:"Er las ein Buch vor dem Schlafengehen." },
  { words:["She","sang","a","song","at","the","party."],                 de:"Sie sang ein Lied auf der Party." },
  { words:["I","forgot","my","keys","at","home."],                       de:"Ich vergaß meine Schlüssel zu Hause." },
  { words:["They","flew","to","London","last","month."],                 de:"Sie flogen letzten Monat nach London." },
  { words:["My","dad","drove","us","to","the","airport."],               de:"Mein Vater fuhr uns zum Flughafen." },
  { words:["She","found","her","wallet","under","the","sofa."],          de:"Sie fand ihre Brieftasche unter dem Sofa." },
  { words:["He","taught","English","at","our","school."],                de:"Er lehrte Englisch an unserer Schule." },
  { words:["I","spoke","to","the","teacher","after","class."],           de:"Ich sprach nach dem Unterricht mit dem Lehrer." },
  { words:["They","built","a","snowman","in","the","garden."],           de:"Sie bauten einen Schneemann im Garten." },
  { words:["She","wore","a","red","dress","to","the","party."],          de:"Sie trug ein rotes Kleid zur Party." },
  { words:["He","fell","off","his","bike","this","morning."],            de:"Er fiel heute Morgen von seinem Fahrrad." },
  { words:["We","had","pizza","for","lunch","today."],                   de:"Wir aßen heute Mittag Pizza." },
  { words:["The","cat","sat","on","the","warm","roof."],                 de:"Die Katze saß auf dem warmen Dach." },
  { words:["I","gave","my","friend","a","birthday","present."],          de:"Ich gab meinem Freund ein Geburtstagsgeschenk." },
  { words:["She","took","the","bus","to","work."],                       de:"Sie nahm den Bus zur Arbeit." },
  { words:["He","won","the","race","by","two","seconds."],               de:"Er gewann das Rennen um zwei Sekunden." },
  { words:["They","spent","the","day","at","the","beach."],              de:"Sie verbrachten den Tag am Strand." },
  { words:["My","brother","broke","his","arm","playing","football."],    de:"Mein Bruder brach sich beim Fußball den Arm." },
  { words:["She","made","a","cake","for","my","birthday."],              de:"Sie backte einen Kuchen für meinen Geburtstag." },
  { words:["I","woke","up","early","this","morning."],                   de:"Ich wachte heute Morgen früh auf." },
  { words:["He","drank","three","glasses","of","water."],                de:"Er trank drei Gläser Wasser." },
  { words:["The","baby","slept","for","ten","hours."],                   de:"Das Baby schlief zehn Stunden." },
  { words:["We","met","our","neighbours","at","the","park."],            de:"Wir trafen unsere Nachbarn im Park." },
  { words:["She","sent","me","a","text","message."],                     de:"Sie schickte mir eine Textnachricht." },
  { words:["He","lost","his","phone","on","the","train."],               de:"Er verlor sein Handy im Zug." },
  { words:["They","brought","food","to","the","picnic."],                de:"Sie brachten Essen zum Picknick." },
  { words:["I","thought","about","you","all","day."],                    de:"Ich dachte den ganzen Tag an dich." },
  { words:["She","heard","a","strange","noise","at","night."],           de:"Sie hörte nachts ein seltsames Geräusch." },
  { words:["He","kept","the","door","open","for","me."],                 de:"Er hielt die Tür für mich auf." },
  { words:["We","left","the","house","at","eight","o'clock."],           de:"Wir verließen das Haus um acht Uhr." },
  { words:["The","teacher","told","us","a","funny","story."],            de:"Der Lehrer erzählte uns eine lustige Geschichte." },
  { words:["I","sold","my","old","computer","online."],                  de:"Ich verkaufte meinen alten Computer online." },
  { words:["She","stood","at","the","bus","stop","for","ten","minutes."],de:"Sie stand zehn Minuten an der Bushaltestelle." },
  { words:["He","held","the","baby","very","carefully."],                de:"Er hielt das Baby sehr vorsichtig." },
  { words:["They","chose","a","new","name","for","the","cat."],          de:"Sie wählten einen neuen Namen für die Katze." },
  { words:["I","paid","twenty","euros","for","the","book."],             de:"Ich zahlte zwanzig Euro für das Buch." },
  { words:["She","drew","a","beautiful","picture","of","the","garden."], de:"Sie zeichnete ein schönes Bild des Gartens." },
  { words:["He","grew","vegetables","in","his","garden."],               de:"Er baute Gemüse in seinem Garten an." },
  { words:["We","caught","the","last","bus","home."],                    de:"Wir nahmen den letzten Bus nach Hause." },
  { words:["I","put","the","bag","on","the","kitchen","table."],         de:"Ich stellte die Tasche auf den Küchentisch." }
],

/* ================================================================
   VOCAB – 100 Alltagswörter (9 Themen)
   ================================================================ */
VOCAB: [
  /* Essen (20) */
  {en:"apple",      de:"Apfel",        pron:"[ˈæpəl]",       t:"Essen"},
  {en:"bread",      de:"Brot",         pron:"[brɛd]",         t:"Essen"},
  {en:"water",      de:"Wasser",       pron:"[ˈwɔːtər]",      t:"Essen"},
  {en:"milk",       de:"Milch",        pron:"[mɪlk]",         t:"Essen"},
  {en:"egg",        de:"Ei",           pron:"[ɛɡ]",           t:"Essen"},
  {en:"cheese",     de:"Käse",         pron:"[tʃiːz]",        t:"Essen"},
  {en:"butter",     de:"Butter",       pron:"[ˈbʌtər]",       t:"Essen"},
  {en:"sugar",      de:"Zucker",       pron:"[ˈʃʊɡər]",       t:"Essen"},
  {en:"salt",       de:"Salz",         pron:"[sɔːlt]",        t:"Essen"},
  {en:"meat",       de:"Fleisch",      pron:"[miːt]",         t:"Essen"},
  {en:"chicken",    de:"Hähnchen",     pron:"[ˈtʃɪkɪn]",      t:"Essen"},
  {en:"fish",       de:"Fisch",        pron:"[fɪʃ]",          t:"Essen"},
  {en:"soup",       de:"Suppe",        pron:"[suːp]",         t:"Essen"},
  {en:"rice",       de:"Reis",         pron:"[raɪs]",         t:"Essen"},
  {en:"pasta",      de:"Nudeln",       pron:"[ˈpæstə]",       t:"Essen"},
  {en:"cake",       de:"Kuchen",       pron:"[keɪk]",         t:"Essen"},
  {en:"coffee",     de:"Kaffee",       pron:"[ˈkɒfi]",        t:"Essen"},
  {en:"tea",        de:"Tee",          pron:"[tiː]",          t:"Essen"},
  {en:"juice",      de:"Saft",         pron:"[dʒuːs]",        t:"Essen"},
  {en:"fruit",      de:"Obst",         pron:"[fruːt]",        t:"Essen"},
  /* Zuhause (15) */
  {en:"house",      de:"Haus",         pron:"[haʊs]",         t:"Zuhause"},
  {en:"room",       de:"Zimmer",       pron:"[ruːm]",         t:"Zuhause"},
  {en:"bed",        de:"Bett",         pron:"[bɛd]",          t:"Zuhause"},
  {en:"chair",      de:"Stuhl",        pron:"[tʃɛər]",        t:"Zuhause"},
  {en:"table",      de:"Tisch",        pron:"[ˈteɪbəl]",      t:"Zuhause"},
  {en:"window",     de:"Fenster",      pron:"[ˈwɪndəʊ]",      t:"Zuhause"},
  {en:"door",       de:"Tür",          pron:"[dɔː]",          t:"Zuhause"},
  {en:"kitchen",    de:"Küche",        pron:"[ˈkɪtʃɪn]",      t:"Zuhause"},
  {en:"bathroom",   de:"Badezimmer",   pron:"[ˈbɑːθruːm]",    t:"Zuhause"},
  {en:"garden",     de:"Garten",       pron:"[ˈɡɑːdən]",      t:"Zuhause"},
  {en:"floor",      de:"Boden",        pron:"[flɔː]",         t:"Zuhause"},
  {en:"wall",       de:"Wand",         pron:"[wɔːl]",         t:"Zuhause"},
  {en:"lamp",       de:"Lampe",        pron:"[læmp]",         t:"Zuhause"},
  {en:"sofa",       de:"Sofa",         pron:"[ˈsəʊfə]",       t:"Zuhause"},
  {en:"shelf",      de:"Regal",        pron:"[ʃɛlf]",         t:"Zuhause"},
  /* Einkaufen (10) */
  {en:"shop",       de:"Laden",        pron:"[ʃɒp]",          t:"Einkaufen"},
  {en:"money",      de:"Geld",         pron:"[ˈmʌni]",        t:"Einkaufen"},
  {en:"price",      de:"Preis",        pron:"[praɪs]",        t:"Einkaufen"},
  {en:"cheap",      de:"billig",       pron:"[tʃiːp]",        t:"Einkaufen"},
  {en:"expensive",  de:"teuer",        pron:"[ɪkˈspɛnsɪv]",   t:"Einkaufen"},
  {en:"buy",        de:"kaufen",       pron:"[baɪ]",          t:"Einkaufen"},
  {en:"sell",       de:"verkaufen",    pron:"[sɛl]",          t:"Einkaufen"},
  {en:"market",     de:"Markt",        pron:"[ˈmɑːkɪt]",      t:"Einkaufen"},
  {en:"bag",        de:"Tasche",       pron:"[bæɡ]",          t:"Einkaufen"},
  {en:"receipt",    de:"Quittung",     pron:"[rɪˈsiːt]",      t:"Einkaufen"},
  /* Familie (10) */
  {en:"mother",     de:"Mutter",       pron:"[ˈmʌðər]",       t:"Familie"},
  {en:"father",     de:"Vater",        pron:"[ˈfɑːðər]",      t:"Familie"},
  {en:"sister",     de:"Schwester",    pron:"[ˈsɪstər]",      t:"Familie"},
  {en:"brother",    de:"Bruder",       pron:"[ˈbrʌðər]",      t:"Familie"},
  {en:"grandmother",de:"Großmutter",   pron:"[ˈɡrænd,mʌðər]", t:"Familie"},
  {en:"grandfather",de:"Großvater",    pron:"[ˈɡrænd,fɑːðər]",t:"Familie"},
  {en:"aunt",       de:"Tante",        pron:"[ɑːnt]",         t:"Familie"},
  {en:"uncle",      de:"Onkel",        pron:"[ˈʌŋkəl]",       t:"Familie"},
  {en:"cousin",     de:"Cousin/-e",    pron:"[ˈkʌzən]",       t:"Familie"},
  {en:"family",     de:"Familie",      pron:"[ˈfæməli]",      t:"Familie"},
  /* Schule (10) */
  {en:"school",     de:"Schule",       pron:"[skuːl]",        t:"Schule"},
  {en:"teacher",    de:"Lehrer/in",    pron:"[ˈtiːtʃər]",     t:"Schule"},
  {en:"student",    de:"Schüler/in",   pron:"[ˈstjuːdənt]",   t:"Schule"},
  {en:"book",       de:"Buch",         pron:"[bʊk]",          t:"Schule"},
  {en:"pencil",     de:"Bleistift",    pron:"[ˈpɛnsəl]",      t:"Schule"},
  {en:"class",      de:"Klasse",       pron:"[klɑːs]",        t:"Schule"},
  {en:"lesson",     de:"Stunde",       pron:"[ˈlɛsən]",       t:"Schule"},
  {en:"homework",   de:"Hausaufgaben", pron:"[ˈhəʊm,wɜːk]",   t:"Schule"},
  {en:"test",       de:"Test/Prüfung", pron:"[tɛst]",         t:"Schule"},
  {en:"grade",      de:"Note",         pron:"[ɡreɪd]",        t:"Schule"},
  /* Körper (10) */
  {en:"head",       de:"Kopf",         pron:"[hɛd]",          t:"Körper"},
  {en:"eye",        de:"Auge",         pron:"[aɪ]",           t:"Körper"},
  {en:"ear",        de:"Ohr",          pron:"[ɪər]",          t:"Körper"},
  {en:"nose",       de:"Nase",         pron:"[nəʊz]",         t:"Körper"},
  {en:"mouth",      de:"Mund",         pron:"[maʊθ]",         t:"Körper"},
  {en:"hand",       de:"Hand",         pron:"[hænd]",         t:"Körper"},
  {en:"arm",        de:"Arm",          pron:"[ɑːm]",          t:"Körper"},
  {en:"leg",        de:"Bein",         pron:"[lɛɡ]",          t:"Körper"},
  {en:"foot",       de:"Fuß",          pron:"[fʊt]",          t:"Körper"},
  {en:"heart",      de:"Herz",         pron:"[hɑːt]",         t:"Körper"},
  /* Farben (10) */
  {en:"red",        de:"rot",          pron:"[rɛd]",          t:"Farben"},
  {en:"blue",       de:"blau",         pron:"[bluː]",         t:"Farben"},
  {en:"green",      de:"grün",         pron:"[ɡriːn]",        t:"Farben"},
  {en:"yellow",     de:"gelb",         pron:"[ˈjɛləʊ]",       t:"Farben"},
  {en:"black",      de:"schwarz",      pron:"[blæk]",         t:"Farben"},
  {en:"white",      de:"weiß",         pron:"[waɪt]",         t:"Farben"},
  {en:"orange",     de:"orange",       pron:"[ˈɒrɪndʒ]",      t:"Farben"},
  {en:"purple",     de:"lila",         pron:"[ˈpɜːpəl]",      t:"Farben"},
  {en:"brown",      de:"braun",        pron:"[braʊn]",        t:"Farben"},
  {en:"pink",       de:"rosa",         pron:"[pɪŋk]",         t:"Farben"},
  /* Zahlen (10) */
  {en:"one",        de:"eins",         pron:"[wʌn]",          t:"Zahlen"},
  {en:"two",        de:"zwei",         pron:"[tuː]",          t:"Zahlen"},
  {en:"three",      de:"drei",         pron:"[θriː]",         t:"Zahlen"},
  {en:"four",       de:"vier",         pron:"[fɔː]",          t:"Zahlen"},
  {en:"five",       de:"fünf",         pron:"[faɪv]",         t:"Zahlen"},
  {en:"six",        de:"sechs",        pron:"[sɪks]",         t:"Zahlen"},
  {en:"seven",      de:"sieben",       pron:"[ˈsɛvən]",       t:"Zahlen"},
  {en:"eight",      de:"acht",         pron:"[eɪt]",          t:"Zahlen"},
  {en:"nine",       de:"neun",         pron:"[naɪn]",         t:"Zahlen"},
  {en:"ten",        de:"zehn",         pron:"[tɛn]",          t:"Zahlen"},
  /* Zeit (10) */
  {en:"morning",    de:"Morgen",       pron:"[ˈmɔːnɪŋ]",     t:"Zeit"},
  {en:"afternoon",  de:"Nachmittag",   pron:"[ˌɑːftəˈnuːn]", t:"Zeit"},
  {en:"evening",    de:"Abend",        pron:"[ˈiːvnɪŋ]",     t:"Zeit"},
  {en:"night",      de:"Nacht",        pron:"[naɪt]",         t:"Zeit"},
  {en:"today",      de:"heute",        pron:"[təˈdeɪ]",       t:"Zeit"},
  {en:"yesterday",  de:"gestern",      pron:"[ˈjɛstədeɪ]",   t:"Zeit"},
  {en:"tomorrow",   de:"morgen",       pron:"[təˈmɒrəʊ]",    t:"Zeit"},
  {en:"week",       de:"Woche",        pron:"[wiːk]",         t:"Zeit"},
  {en:"month",      de:"Monat",        pron:"[mʌnθ]",         t:"Zeit"},
  {en:"year",       de:"Jahr",         pron:"[jɪər]",         t:"Zeit"}
],

/* ================================================================
   PRONOUNS – 40 Übungen (Subjekt/Objekt/Possessiv)
   ================================================================ */
PRONOUNS: [
  /* Subjektpronomen (14) */
  {pre:"",                           post:" love to play football.",            ans:"I",     type:"subject",    de:"Ich liebe Fußball spielen."},
  {pre:"",                           post:" is my best friend.",                ans:"She",   type:"subject",    de:"Sie ist meine beste Freundin."},
  {pre:"",                           post:" has a big dog.",                    ans:"He",    type:"subject",    de:"Er hat einen großen Hund."},
  {pre:"",                           post:" are late for school today.",        ans:"They",  type:"subject",    de:"Sie kommen heute zu spät zur Schule."},
  {pre:"",                           post:" is very cold outside.",             ans:"It",    type:"subject",    de:"Es ist sehr kalt draußen."},
  {pre:"",                           post:" go to the park every Sunday.",      ans:"We",    type:"subject",    de:"Wir gehen jeden Sonntag in den Park."},
  {pre:"",                           post:" speak English very well.",          ans:"You",   type:"subject",    de:"Du sprichst sehr gut Englisch."},
  {pre:"My dad works in an office.", post:" comes home at six o'clock.",        ans:"He",    type:"subject",    de:"Er kommt um sechs nach Hause."},
  {pre:"Lisa called me yesterday.",  post:" wanted to ask a question.",         ans:"She",   type:"subject",    de:"Sie wollte eine Frage stellen."},
  {pre:"",                           post:" are my favourite band!",            ans:"They",  type:"subject",    de:"Sie sind meine Lieblingsband!"},
  {pre:"",                           post:" have two sisters and one brother.", ans:"I",     type:"subject",    de:"Ich habe zwei Schwestern und einen Bruder."},
  {pre:"",                           post:" is a small black cat.",             ans:"It",    type:"subject",    de:"Es ist eine kleine schwarze Katze."},
  {pre:"",                           post:" are both really good students.",    ans:"We",    type:"subject",    de:"Wir sind beide wirklich gute Schüler."},
  {pre:"Tom is very kind.",          post:" always helps his friends.",         ans:"He",    type:"subject",    de:"Er hilft immer seinen Freunden."},
  /* Objektpronomen (13) */
  {pre:"Please help",                post:".",                                  ans:"me",    type:"object",     de:"Bitte hilf mir."},
  {pre:"She likes",                  post:" very much.",                        ans:"him",   type:"object",     de:"Sie mag ihn sehr."},
  {pre:"I called",                   post:" yesterday.",                        ans:"her",   type:"object",     de:"Ich habe sie gestern angerufen."},
  {pre:"The teacher saw",            post:" in the park.",                      ans:"us",    type:"object",     de:"Der Lehrer sah uns im Park."},
  {pre:"Can you see",                post:" over there?",                       ans:"them",  type:"object",     de:"Kannst du sie dort drüben sehen?"},
  {pre:"My mum gave",                post:" a big present.",                    ans:"me",    type:"object",     de:"Meine Mutter gab mir ein großes Geschenk."},
  {pre:"I don't know",               post:" very well.",                        ans:"him",   type:"object",     de:"Ich kenne ihn nicht sehr gut."},
  {pre:"She told",                   post:" a funny story.",                    ans:"us",    type:"object",     de:"Sie erzählte uns eine lustige Geschichte."},
  {pre:"The dog followed",           post:" all the way home.",                 ans:"her",   type:"object",     de:"Der Hund folgte ihr den ganzen Weg nach Hause."},
  {pre:"Can I help",                 post:"?",                                  ans:"you",   type:"object",     de:"Kann ich dir helfen?"},
  {pre:"We invited",                 post:" to our party.",                     ans:"them",  type:"object",     de:"Wir haben sie zu unserer Party eingeladen."},
  {pre:"I found",                    post:" under the sofa.",                   ans:"it",    type:"object",     de:"Ich fand es unter dem Sofa."},
  {pre:"My teacher always praises",  post:" in front of the class.",            ans:"me",    type:"object",     de:"Mein Lehrer lobt mich immer vor der Klasse."},
  /* Possessivpronomen (13) */
  {pre:"This is",                    post:" new book.",                         ans:"my",    type:"possessive", de:"Das ist mein neues Buch."},
  {pre:"Is this",                    post:" pencil?",                           ans:"your",  type:"possessive", de:"Ist das dein Bleistift?"},
  {pre:"Tom loves",                  post:" dog.",                              ans:"his",   type:"possessive", de:"Tom liebt seinen Hund."},
  {pre:"She lost",                   post:" keys again.",                       ans:"her",   type:"possessive", de:"Sie hat wieder ihre Schlüssel verloren."},
  {pre:"The cat drinks",             post:" milk every morning.",               ans:"its",   type:"possessive", de:"Die Katze trinkt jeden Morgen ihre Milch."},
  {pre:"We did",                     post:" homework together.",                ans:"our",   type:"possessive", de:"Wir haben unsere Hausaufgaben zusammen gemacht."},
  {pre:"They painted",               post:" house blue.",                       ans:"their", type:"possessive", de:"Sie haben ihr Haus blau gestrichen."},
  {pre:"I forgot",                   post:" bag at school.",                    ans:"my",    type:"possessive", de:"Ich habe meine Tasche in der Schule vergessen."},
  {pre:"He plays with",              post:" friends every afternoon.",          ans:"his",   type:"possessive", de:"Er spielt jeden Nachmittag mit seinen Freunden."},
  {pre:"She cleaned",                post:" room before dinner.",               ans:"her",   type:"possessive", de:"Sie hat ihr Zimmer vor dem Abendessen aufgeräumt."},
  {pre:"We love",                    post:" new English teacher.",              ans:"our",   type:"possessive", de:"Wir lieben unsere neue Englischlehrerin."},
  {pre:"Can I borrow",               post:" pencil for a moment?",              ans:"your",  type:"possessive", de:"Kann ich kurz deinen Bleistift ausleihen?"},
  {pre:"The dog wagged",             post:" tail happily.",                     ans:"its",   type:"possessive", de:"Der Hund wedelte freudig mit seinem Schwanz."}
],

/* ================================================================
   GRAMMAR_QS – 40 Fragen (4 Themen × 10)
   ================================================================ */
GRAMMAR_QS: [
  /* Satzbau (10) */
  {sub:'satzbau', q:'Welcher Satz ist grammatisch korrekt?',
   opts:['She always drinks coffee in the morning.','She drinks always coffee in the morning.','She drinks coffee always in the morning.','Always coffee she drinks in the morning.'],
   ans:0, rule:'Häufigkeitsadverbien (always, never, often) stehen VOR dem Hauptverb.'},
  {sub:'satzbau', q:'Welcher Satz ist grammatisch korrekt?',
   opts:['Do you like football?','You do like football?','Like you football?','Do you likes football?'],
   ans:0, rule:'Ja/Nein-Fragen im Simple Present: Do/Does + Subjekt + Infinitiv?'},
  {sub:'satzbau', q:'Welcher Satz ist grammatisch korrekt?',
   opts:['She does not eat meat.','She not does eat meat.','She eats not meat.','Not she eats meat.'],
   ans:0, rule:'Verneinung im Simple Present: Subjekt + do/does + not + Infinitiv.'},
  {sub:'satzbau', q:'Welcher Satz ist grammatisch korrekt?',
   opts:['He has a big red car.','He has red big car.','He has a car big red.','He has big a red car.'],
   ans:0, rule:'Adjektive stehen VOR dem Nomen: a big red car.'},
  {sub:'satzbau', q:'Welcher Satz ist grammatisch korrekt?',
   opts:['I went to the cinema yesterday.','I went yesterday to the cinema.','Yesterday I to the cinema went.','I to the cinema yesterday went.'],
   ans:0, rule:'Zeitangaben stehen in der Regel am Ende des Satzes.'},
  {sub:'satzbau', q:'Welcher Satz ist grammatisch korrekt?',
   opts:['She gave me a present.','She gave a present me.','She me gave a present.','Me a present she gave.'],
   ans:0, rule:'Reihenfolge beim indirekten Objekt: give + Person + Sache.'},
  {sub:'satzbau', q:'Welcher Satz ist grammatisch korrekt?',
   opts:['Did you see the film?','You did see the film?','Did you saw the film?','Saw you the film?'],
   ans:0, rule:'Fragen im Simple Past: Did + Subjekt + Infinitiv (nicht Past-Form!).'},
  {sub:'satzbau', q:'Welcher Satz ist grammatisch korrekt?',
   opts:['He is always happy.','He always is happy.','Always he happy is.','He happy is always.'],
   ans:0, rule:'Bei "to be" steht das Häufigkeitsadverb NACH dem Verb: He is always...'},
  {sub:'satzbau', q:'Welcher Satz ist grammatisch korrekt?',
   opts:['They play football every day.','They play every day football.','Every day they football play.','Football they play every day.'],
   ans:0, rule:'Englische Grundstruktur: Subjekt – Verb – Objekt – Zeitangabe.'},
  {sub:'satzbau', q:'Welcher Satz ist grammatisch korrekt?',
   opts:["She doesn't like spicy food.",'She likes not spicy food.','She not likes spicy food.','She does not likes spicy food.'],
   ans:0, rule:"Verneinung: doesn't + Infinitiv (kein -s am Hauptverb!)."},

  /* Present vs. Past (10) */
  {sub:'tenses', q:'Ergänze die richtige Zeitform:\n"Yesterday she ___ to school."',
   opts:['went','goes','is going','has gone'],
   ans:0, rule:"'Yesterday' zeigt abgeschlossene Vergangenheit → Simple Past."},
  {sub:'tenses', q:'Ergänze die richtige Zeitform:\n"Every morning I ___ breakfast."',
   opts:['eat','ate','was eating','have eaten'],
   ans:0, rule:"'Every morning' = regelmäßige Gewohnheit → Simple Present."},
  {sub:'tenses', q:'Ergänze die richtige Zeitform:\n"She ___ her keys last night."',
   opts:['lost','loses','is losing','lose'],
   ans:0, rule:"'Last night' = abgeschlossene Vergangenheit → Simple Past."},
  {sub:'tenses', q:'Ergänze die richtige Zeitform:\n"He ___ football every Saturday."',
   opts:['plays','played','was playing','play'],
   ans:0, rule:"'Every Saturday' + 3. Person Singular → Simple Present (plays)."},
  {sub:'tenses', q:'Ergänze die richtige Zeitform:\n"We ___ pizza for dinner last Friday."',
   opts:['had','have','are having','has'],
   ans:0, rule:"'Last Friday' = abgeschlossene Vergangenheit → Simple Past (had)."},
  {sub:'tenses', q:'Ergänze die richtige Zeitform:\n"She usually ___ the bus to school."',
   opts:['takes','took','has taken','is taking'],
   ans:0, rule:"'Usually' = regelmäßige Handlung + 3. Person → Simple Present (takes)."},
  {sub:'tenses', q:'Ergänze die richtige Zeitform:\n"They ___ a snowman last winter."',
   opts:['built','build','builds','are building'],
   ans:0, rule:"'Last winter' = abgeschlossene Vergangenheit → Simple Past (built)."},
  {sub:'tenses', q:'Ergänze die richtige Zeitform:\n"My dad ___ to work by car every day."',
   opts:['drives','drove','is driving','drive'],
   ans:0, rule:"'Every day' + 3. Person Singular → Simple Present (drives)."},
  {sub:'tenses', q:'Ergänze die richtige Zeitform:\n"I ___ a great film on TV last night."',
   opts:['saw','see','sees','was seen'],
   ans:0, rule:"'Last night' = abgeschlossene Vergangenheit → Simple Past (saw)."},
  {sub:'tenses', q:'Ergänze die richtige Zeitform:\n"She ___ to school on Mondays."',
   opts:["doesn't go",'not goes',"didn't go",'not go'],
   ans:0, rule:"Verneinung Simple Present 3. Person: doesn't + Infinitiv."},

  /* To be (10) */
  {sub:'tobe', q:'Ergänze: "I ___ a student."',
   opts:['am','is','are','was'],   ans:0, rule:'To be (Präsens): I am / you are / he-she-it is.'},
  {sub:'tobe', q:'Ergänze: "She ___ my best friend."',
   opts:['is','am','are','were'],  ans:0, rule:'He / She / It → IS (Simple Present).'},
  {sub:'tobe', q:'Ergänze: "They ___ at school now."',
   opts:['are','is','am','was'],   ans:0, rule:'We / You / They → ARE (Simple Present).'},
  {sub:'tobe', q:'Ergänze: "We ___ happy to be here."',
   opts:['are','is','am','were'],  ans:0, rule:'We → ARE (Simple Present).'},
  {sub:'tobe', q:'Ergänze: "Yesterday it ___ very cold."',
   opts:['was','is','were','am'],  ans:0, rule:'Simple Past (I / He / She / It): WAS.'},
  {sub:'tobe', q:'Ergänze: "We ___ at the park yesterday."',
   opts:['were','was','are','am'], ans:0, rule:'Simple Past (We / You / They): WERE.'},
  {sub:'tobe', q:'Ergänze: "He ___ not at home last night."',
   opts:['was','were','is','am'],  ans:0, rule:"Verneinung 'to be' Past (He/She/It): was not (wasn't)."},
  {sub:'tobe', q:'Ergänze: "___ you at the party on Saturday?"',
   opts:['Were','Was','Are','Is'], ans:0, rule:"Frage Simple Past (We/You/They): Were you...?"},
  {sub:'tobe', q:'Ergänze: "The children ___ very excited about the trip."',
   opts:['were','was','is','am'],  ans:0, rule:'The children = they → Simple Past: were.'},
  {sub:'tobe', q:'Ergänze: "___ she at school today?"',
   opts:['Is','Are','Was','Were'], ans:0, rule:'Frage Simple Present (He/She/It): Is she...?'},

  /* Kurzantworten (10) */
  {sub:'short', q:'Richtige Kurzantwort:\n"Are you happy?" – "Yes, ___"',
   opts:['I am.','I do.','I have.','I was.'],   ans:0, rule:"Kurzantwort mit 'to be': Yes, I am. / No, I'm not."},
  {sub:'short', q:'Richtige Kurzantwort:\n"Does she like pizza?" – "Yes, ___"',
   opts:['she does.','she is.','she likes.','she did.'],   ans:0, rule:"Kurzantwort Simple Present (Does): Yes, she does."},
  {sub:'short', q:'Richtige Kurzantwort:\n"Did they go to school?" – "No, ___"',
   opts:["they didn't.",'they don\'t.',"they weren't.",'they hadn\'t.'],
   ans:0, rule:"Kurzantwort Simple Past: No, they didn't."},
  {sub:'short', q:'Richtige Kurzantwort:\n"Were you at home?" – "Yes, ___"',
   opts:['I was.','I did.','I am.','I had.'],   ans:0, rule:"Kurzantwort 'to be' Past: Yes, I was. / No, I wasn't."},
  {sub:'short', q:'Richtige Kurzantwort:\n"Do you like football?" – "No, ___"',
   opts:["I don't.",'I am not.',"I didn't.",'I wasn\'t.'],
   ans:0, rule:"Kurzantwort Simple Present: No, I don't. / Yes, I do."},
  {sub:'short', q:'Richtige Kurzantwort:\n"Is he your brother?" – "No, ___"',
   opts:["he isn't.",'he doesn\'t.',"he wasn't.",'he didn\'t.'],
   ans:0, rule:"Kurzantwort 'to be' Present: No, he isn't. / Yes, he is."},
  {sub:'short', q:'Richtige Kurzantwort:\n"Did you eat breakfast?" – "Yes, ___"',
   opts:['I did.','I was.','I am.','I have.'],  ans:0, rule:"Kurzantwort Simple Past: Yes, I did. / No, I didn't."},
  {sub:'short', q:'Richtige Kurzantwort:\n"Are they your friends?" – "Yes, ___"',
   opts:['they are.','they do.','they were.','they have.'],
   ans:0, rule:"Kurzantwort 'to be' Present: Yes, they are. / No, they aren't."},
  {sub:'short', q:'Richtige Kurzantwort:\n"Does he play the guitar?" – "No, ___"',
   opts:["he doesn't.",'he isn\'t.',"he didn't.",'he hasn\'t.'],
   ans:0, rule:"Kurzantwort Simple Present (Does): No, he doesn't."},
  {sub:'short', q:'Richtige Kurzantwort:\n"Was she at the party?" – "No, ___"',
   opts:["she wasn't.",'she didn\'t.',"she isn't.",'she don\'t.'],
   ans:0, rule:"Kurzantwort 'to be' Past: No, she wasn't. / Yes, she was."}
],

/* ================================================================
   EXAM_QS – 40 Prüfungsfragen (4 Themen × 10)
   ================================================================ */
EXAM_QS: [
  /* Sich vorstellen (10) */
  {sub:'intro', q:'Wie sagt man auf Englisch: "Wie heißt du?"',
   opts:['What is your name?','What are you called?','How are you named?','How do you call yourself?'],
   ans:0, rule:"'Wie heißt du?' = What is your name? (oder: What's your name?)"},
  {sub:'intro', q:'Ergänze: "My name ___ Anna."',
   opts:['is','am','are','was'], ans:0, rule:"My name = 3. Person Singular → My name IS Anna."},
  {sub:'intro', q:'Übersetze: "Ich bin 14 Jahre alt."',
   opts:['I am 14 years old.','I have 14 years.','I am 14 year old.','I got 14 years.'],
   ans:0, rule:"Im Englischen: I am 14 years old. (nicht 'have' wie im Deutschen!)"},
  {sub:'intro', q:'Wie fragt man: "Wie alt bist du?"',
   opts:['How old are you?','How many years are you?','What is your years?','How much old are you?'],
   ans:0, rule:"'Wie alt bist du?' = How old are you?"},
  {sub:'intro', q:'Übersetze: "Ich komme aus Deutschland."',
   opts:['I come from Germany.','I am from Germany coming.','I come of Germany.','From Germany I come.'],
   ans:0, rule:"'Ich komme aus...' = I come from... / I am from..."},
  {sub:'intro', q:'Wie fragt man: "Woher kommst du?"',
   opts:['Where are you from?','From where come you?','Where you are from?','Where do you come?'],
   ans:0, rule:"'Woher kommst du?' = Where are you from? / Where do you come from?"},
  {sub:'intro', q:'Übersetze: "Mein Hobby ist Fußball spielen."',
   opts:['My hobby is playing football.','My hobby is play football.','My hobby is football to play.','I hobby is playing football.'],
   ans:0, rule:"Nach 'is' steht das Verb als Gerundium (-ing): My hobby is playing..."},
  {sub:'intro', q:'Vervollständige: "Hello, ___ Anna. Nice to meet you."',
   opts:["I'm",'my name are','I were','calls me'],
   ans:0, rule:"Kurzform für 'Ich bin': I'm (= I am). → Hello, I'm Anna."},
  {sub:'intro', q:'Übersetze: "Ich gehe in die 8. Klasse."',
   opts:['I am in Year 8.','I go to the 8th class.','I go in the 8 class.','I learn in class 8.'],
   ans:0, rule:"Im Britischen Englisch: I am in Year 8. (Amerikanisch: I am in 8th grade.)"},
  {sub:'intro', q:'Wie antwortet man auf "How are you?"\nAntwort: "___, thank you."',
   opts:['Fine','Good, I','I fine','Yes, fine'],
   ans:0, rule:"'Wie geht es dir?' – Fine, thank you. / I'm fine, thanks."},

  /* Familie (10) */
  {sub:'family', q:'Übersetze: "Ich habe eine Schwester."',
   opts:['I have a sister.','I has a sister.','I got a sister.','I am having a sister.'],
   ans:0, rule:"'haben' im Englischen = have. Simple Present: I have, she has."},
  {sub:'family', q:'Übersetze: "Hast du Geschwister?"',
   opts:['Do you have any siblings?','Have you siblings?','Do you got siblings?','Has you siblings?'],
   ans:0, rule:"'Hast du?' = Do you have...? ('any' macht die Frage natürlicher.)"},
  {sub:'family', q:'Übersetze: "Mein Vater heißt Thomas."',
   opts:["My father's name is Thomas.",'My father called Thomas.','My father name is Thomas.','My father has name Thomas.'],
   ans:0, rule:"'...heißt...' = ...name is... Possessiv: father's name is..."},
  {sub:'family', q:'Übersetze: "Ich bin ein Einzelkind."',
   opts:['I am an only child.','I am a single child.','I am a lonely child.','I am the only child.'],
   ans:0, rule:"'Einzelkind' = only child. → I am an only child."},
  {sub:'family', q:'Übersetze: "Mein Bruder ist älter als ich."',
   opts:['My brother is older than me.','My brother is more old than me.','My brother is older as me.','My brother is elder than me.'],
   ans:0, rule:"Komparativ von 'old': older than (nicht 'more old' oder 'elder')."},
  {sub:'family', q:'Übersetze: "Meine Großmutter wohnt bei uns."',
   opts:['My grandmother lives with us.','My grandmother lives by us.','My grandmother lives at us.','My grandma is living at our.'],
   ans:0, rule:"'bei uns wohnen' = live with us."},
  {sub:'family', q:'Übersetze: "Ich habe zwei Cousinen."',
   opts:['I have two cousins.','I have two cousin.','I got two cousins.','I have two female cousins.'],
   ans:0, rule:"'Cousinen' = cousins (kein Geschlechtsunterschied im Englischen)."},
  {sub:'family', q:'Übersetze: "Meine Mutter arbeitet als Lehrerin."',
   opts:['My mother works as a teacher.','My mother works like a teacher.','My mother is working as teacher.','My mother work as a teacher.'],
   ans:0, rule:"'als' bei Berufen = as a: works as a teacher."},
  {sub:'family', q:'Wie fragt man: "Wie viele Geschwister hast du?"',
   opts:['How many siblings do you have?','How much siblings have you?','How many siblings are you?','How many sibling do you have?'],
   ans:0, rule:"'Wie viele...?' = How many...? + Plural (siblings, nicht sibling)."},
  {sub:'family', q:'Übersetze: "Mein Hund heißt Rex."',
   opts:["My dog's name is Rex.",'My dog called Rex.','My dog name Rex.','My dog has name Rex.'],
   ans:0, rule:"Possessiv: My dog's name is Rex. (oder: My dog is called Rex.)"},

  /* Wohnort (10) */
  {sub:'home', q:'Übersetze: "Wo wohnst du?"',
   opts:['Where do you live?','Where you live?','Where are you living?','Where live you?'],
   ans:0, rule:"'Wo wohnst du?' = Where do you live? (Simple Present Frage mit do)"},
  {sub:'home', q:'Übersetze: "Ich wohne in Berlin."',
   opts:['I live in Berlin.','I am living in Berlin.','I live at Berlin.','I live on Berlin.'],
   ans:0, rule:"'Ich wohne in...' = I live in... (Präposition 'in' für Städte)."},
  {sub:'home', q:'Übersetze: "Ich wohne in einem Haus."',
   opts:['I live in a house.','I live at a house.','I am living in house.','I live in the house.'],
   ans:0, rule:"'Ich wohne in einem...' = I live in a... (unbestimmter Artikel)."},
  {sub:'home', q:'Übersetze: "Unser Garten ist groß."',
   opts:['Our garden is big.','Our garden is great.','Our garden is tall.','Our garden is high.'],
   ans:0, rule:"'groß' bei Flächen = big / large. (great = großartig, tall/high = hoch)"},
  {sub:'home', q:'Übersetze: "Wir wohnen in der Stadtmitte."',
   opts:['We live in the city centre.','We live in the city middle.','We live at the city centre.','We live inside the city.'],
   ans:0, rule:"'Stadtmitte' = city centre (brit.) / city center (amer.)."},
  {sub:'home', q:'Übersetze: "Die Schule ist in der Nähe."',
   opts:['The school is nearby.','The school is nearly.','The school is next.','The school is close by me.'],
   ans:0, rule:"'in der Nähe' = nearby (Adverb, steht hinter dem Verb)."},
  {sub:'home', q:'Übersetze: "Mein Zimmer ist klein."',
   opts:['My room is small.','My room is little.','My room is tiny.','My room is short.'],
   ans:0, rule:"'klein' für Räume = small (little = wenig/jung, tiny = winzig, short = kurz)."},
  {sub:'home', q:'Übersetze: "Es gibt einen Park in der Nähe."',
   opts:['There is a park nearby.','It gives a park nearby.','There are a park nearby.','There is the park nearby.'],
   ans:0, rule:"'Es gibt' = There is (Singular) / There are (Plural)."},
  {sub:'home', q:'Übersetze: "Unser Haus hat drei Schlafzimmer."',
   opts:['Our house has three bedrooms.','Our house has three sleeping rooms.','Our house have three bedrooms.','Our house is having three bedrooms.'],
   ans:0, rule:"'Schlafzimmer' = bedroom. 3. Pers. Sing.: Our house HAS..."},
  {sub:'home', q:'Übersetze: "Ich mag meine Stadt."',
   opts:['I like my town.','I am like my town.','I liking my town.','I does like my town.'],
   ans:0, rule:"'mögen' = like. Simple Present: I like... (kein 'am' davor!)."},

  /* Wegbeschreibung (10) */
  {sub:'directions', q:'Übersetze: "Geh geradeaus."',
   opts:['Go straight ahead.','Go directly.','Walk directly ahead.','Go straight forward.'],
   ans:0, rule:"'Geradeaus' = straight ahead. Imperativ: Go straight ahead."},
  {sub:'directions', q:'Übersetze: "Biege links ab."',
   opts:['Turn left.','Go to the left.','Turn to the left side.','Bend left.'],
   ans:0, rule:"'Links abbiegen' = Turn left. (kurze Imperativform)"},
  {sub:'directions', q:'Übersetze: "Biege rechts ab."',
   opts:['Turn right.','Go right side.','Turn to right.','Bend right.'],
   ans:0, rule:"'Rechts abbiegen' = Turn right."},
  {sub:'directions', q:'Übersetze: "Die Bank ist um die Ecke."',
   opts:['The bank is around the corner.','The bank is at the corner.','The bank is on the corner.','The bank is behind the corner.'],
   ans:0, rule:"'um die Ecke' = around the corner."},
  {sub:'directions', q:'Wie fragt man: "Wie komme ich zum Bahnhof?"',
   opts:['How do I get to the station?','How come I to the station?','Where do I go the station?','How do I go to the station?'],
   ans:0, rule:"'Wie komme ich zu...?' = How do I get to...?"},
  {sub:'directions', q:'Übersetze: "Geh an der Ampel vorbei."',
   opts:['Go past the traffic lights.','Go before the traffic lights.','Walk at the traffic lights.','Pass the traffic light on.'],
   ans:0, rule:"'an...vorbeigehen' = go past. Ampel = traffic lights."},
  {sub:'directions', q:'Übersetze: "Es ist auf der linken Seite."',
   opts:["It's on the left.",'It is in the left.','It is at the left.','It is the left side.'],
   ans:0, rule:"'auf der linken Seite' = on the left / on the left-hand side."},
  {sub:'directions', q:'Übersetze: "Entschuldigung, wo ist die Post?"',
   opts:['Excuse me, where is the post office?','Sorry, where is the post?','Excuse me, where is the postal office?','Pardon, where the post office is?'],
   ans:0, rule:"'Entschuldigung' = Excuse me. 'Post' = post office."},
  {sub:'directions', q:'Übersetze: "Es ist ungefähr 5 Minuten zu Fuß."',
   opts:["It's about a 5-minute walk.",'It is 5 minutes by foot.','It is around 5 minutes walk.','It takes about 5 minutes foot.'],
   ans:0, rule:"'zu Fuß' = on foot / a walk. 'ungefähr' = about / around."},
  {sub:'directions', q:'Übersetze: "Nimm die zweite Straße links."',
   opts:['Take the second street on the left.','Take the second left street.','Go the second street on left.','Turn second street to the left.'],
   ans:0, rule:"'Nimm die zweite Straße links.' = Take the second street on the left."}
]

}; // END DATA_EASY
