/* ================================================================
   DATA_HARD  –  B1/B2-Niveau (Stufe 3)
   Ergänzt DATA_EASY + DATA_MEDIUM, wird bei Schwierigkeit >= 3 geladen.
   Verben: 34  |  Sätze: 24  |  Vokabeln: 67  |  Pronouns: 5
   Grammar: 18  |  Exam: 16
   ================================================================ */
var DATA_HARD = {

/* ================================================================
   VERBS – 34 Verben (B2)
   Hinweis: beat→easy; bind, breed, burst, cast, cling, creep, deal,
   forbid, forgive, grind, overcome, shrink, spread, swear,
   withdraw→medium. Diese werden hier nicht wiederholt.
   ================================================================ */
VERBS: [
  /* ── Aus Nutzerliste: 14 Verben (nicht in easy/medium) ── */
  {inf:'bear',      past:'bore',      de:'ertragen / gebären / tragen'},
  {inf:'fling',     past:'flung',     de:'schleudern / werfen'},
  {inf:'overtake',  past:'overtook',  de:'überholen / übertreffen'},
  {inf:'spin',      past:'spun',      de:'drehen / spinnen'},
  {inf:'split',     past:'split',     de:'spalten / teilen / aufteilen'},
  {inf:'spring',    past:'sprang',    de:'springen / entspringen'},
  {inf:'stink',     past:'stank',     de:'stinken'},
  {inf:'stride',    past:'strode',    de:'schreiten / ausschreiten'},
  {inf:'strive',    past:'strove',    de:'streben / sich bemühen'},
  {inf:'thrust',    past:'thrust',    de:'stoßen / drängen'},
  {inf:'tread',     past:'trod',      de:'treten / betreten'},
  {inf:'undertake', past:'undertook', de:'unternehmen / übernehmen'},
  {inf:'undergo',   past:'underwent', de:'durchmachen / unterzogen werden'},
  {inf:'wring',     past:'wrung',     de:'wringen / verdrehen'},
  /* ── Weitere B2-Verben (selten / formell) ── */
  {inf:'broadcast', past:'broadcast', de:'senden / übertragen / ausstrahlen'},
  {inf:'forsake',   past:'forsook',   de:'verlassen / aufgeben / im Stich lassen'},
  {inf:'leap',      past:'leapt',     de:'springen / hüpfen'},
  {inf:'mistake',   past:'mistook',   de:'verwechseln / falsch verstehen'},
  {inf:'slay',      past:'slew',      de:'erschlagen / töten'},
  {inf:'slit',      past:'slit',      de:'aufschlitzen / einschneiden'},
  {inf:'string',    past:'strung',    de:'auffädeln / spannen'},
  {inf:'weave',     past:'wove',      de:'weben / flechten'},
  {inf:'befall',    past:'befell',    de:'widerfahren / zuteilwerden'},
  {inf:'cleave',    past:'clove',     de:'spalten / trennen'},
  {inf:'sling',     past:'slung',     de:'schleudern / aufhängen'},
  {inf:'spill',     past:'spilt',     de:'verschütten / vergießen'},
  {inf:'spoil',     past:'spoilt',    de:'verderben / verwöhnen'},
  {inf:'withstand', past:'withstood', de:'widerstehen / standhalten'},
  {inf:'mislay',    past:'mislaid',   de:'verlegen / nicht finden'},
  {inf:'outdo',     past:'outdid',    de:'übertreffen / in den Schatten stellen'},
  {inf:'rebuild',   past:'rebuilt',   de:'wiederaufbauen / neu aufbauen'},
  {inf:'foretell',  past:'foretold',  de:'vorhersagen / prophezeien'},
  {inf:'plead',     past:'pled',      de:'plädieren / flehen / bitten'},
  {inf:'outrun',    past:'outran',    de:'überholen / davonlaufen'}
],

/* ================================================================
   SENTENCES – 24 Sätze (B2: Inversion, Passiv, Konditional, Relativ)
   ================================================================ */
SENTENCES: [
  /* Inversion & Emphase */
  {words:['Not','only','did','she','pass','the','exam,','but','she','also','got','the','highest','mark.'],
   de:'Nicht nur bestand sie die Prüfung, sie bekam auch die höchste Note.'},
  {words:['Had','I','known','about','the','traffic,','I','would','have','left','earlier.'],
   de:'Hätte ich vom Stau gewusst, wäre ich früher losgefahren.'},
  {words:['It','was','not','until','midnight','that','the','guests','finally','left.'],
   de:'Erst um Mitternacht gingen die Gäste schließlich.'},
  {words:['Scarcely','had','she','sat','down','when','the','phone','rang.'],
   de:'Kaum hatte sie sich hingesetzt, da klingelte das Telefon.'},
  {words:['No','sooner','had','he','arrived','home','than','it','started','to','rain','heavily.'],
   de:'Kaum war er nach Hause gekommen, als es anfing, stark zu regnen.'},
  {words:['Little','did','we','know','that','this','would','be','our','last','meeting.'],
   de:'Wir wussten kaum, dass dies unser letztes Treffen sein würde.'},
  {words:['Rarely','do','scientists','agree','on','such','a','controversial','topic.'],
   de:'Selten sind Wissenschaftler bei einem so umstrittenen Thema einer Meinung.'},
  {words:['Only','by','working','together','can','we','solve','the','problems','facing','our','society.'],
   de:'Nur durch gemeinsames Handeln können wir die Probleme unserer Gesellschaft lösen.'},
  /* Komplexes Passiv */
  {words:['The','report','was','said','to','have','been','submitted','last','week.'],
   de:'Der Bericht soll letzte Woche eingereicht worden sein.'},
  {words:['She','is','said','to','have','been','one','of','the','most','influential','scientists','of','her','time.'],
   de:'Sie soll eine der einflussreichsten Wissenschaftlerinnen ihrer Zeit gewesen sein.'},
  {words:['The','project','having','been','completed,','the','team','celebrated','their','success.'],
   de:'Nachdem das Projekt abgeschlossen war, feierte das Team seinen Erfolg.'},
  /* Komparativ-Strukturen */
  {words:['The','more','time','she','spent','abroad,','the','more','fluent','her','English','became.'],
   de:'Je mehr Zeit sie im Ausland verbrachte, desto fließender wurde ihr Englisch.'},
  /* Konditionalsätze */
  {words:['Were','the','funding','to','be','withdrawn,','the','project','would','have','to','be','abandoned.'],
   de:'Sollte die Finanzierung zurückgezogen werden, müsste das Projekt aufgegeben werden.'},
  {words:['Had','she','taken','the','opportunity,','her','career','might','have','developed','differently.'],
   de:'Hätte sie die Gelegenheit genutzt, hätte sich ihre Karriere vielleicht anders entwickelt.'},
  /* Relativsätze */
  {words:['The','treaty,','which','was','signed','in','1648,','brought','an','end','to','years','of','conflict.'],
   de:'Der Vertrag, der 1648 unterzeichnet wurde, beendete jahrelange Konflikte.'},
  {words:['The','scientist','whose','research','changed','our','understanding','of','DNA','received','a','Nobel','Prize.'],
   de:'Die Wissenschaftlerin, deren Forschung unser Verständnis der DNA veränderte, erhielt einen Nobelpreis.'},
  /* Fortgeschrittene Subjunktionen */
  {words:['Provided','that','you','meet','the','deadline,','your','application','will','be','considered.'],
   de:'Vorausgesetzt, dass du die Frist einhältst, wird deine Bewerbung berücksichtigt.'},
  {words:['No','matter','how','hard','he','tried,','he','couldn\'t','seem','to','get','the','right','answer.'],
   de:'Egal wie sehr er es versuchte, er schien nicht die richtige Antwort finden zu können.'},
  /* Komplexe Satzstrukturen */
  {words:['The','research','findings','suggest','that','more','funding','needs','to','be','allocated','to','this','area.'],
   de:'Die Forschungsergebnisse deuten darauf hin, dass mehr Mittel für diesen Bereich bereitgestellt werden müssen.'},
  {words:['Having','been','overlooked','for','promotion','twice,','she','decided','to','look','for','a','new','job.'],
   de:'Nachdem sie zweimal bei der Beförderung übergangen worden war, beschloss sie, sich eine neue Stelle zu suchen.'},
  {words:['So','complex','was','the','problem','that','even','the','experts','struggled','to','find','a','solution.'],
   de:'Das Problem war so komplex, dass selbst die Experten Schwierigkeiten hatten, eine Lösung zu finden.'},
  {words:['The','experiment','is','believed','to','have','caused','significant','damage','to','the','environment.'],
   de:'Es wird angenommen, dass das Experiment erheblichen Schaden an der Umwelt verursacht hat.'},
  {words:['Not','until','she','passed','her','driving','test','did','she','feel','truly','independent.'],
   de:'Erst als sie ihren Führerschein bestanden hatte, fühlte sie sich wirklich unabhängig.'},
  {words:['Under','no','circumstances','should','you','leave','the','building','unattended.'],
   de:'Unter keinen Umständen solltest du das Gebäude unbeaufsichtigt verlassen.'}
],

/* ================================================================
   VOCAB – 67 Wörter (B2-Allg. 27 + Technologie 15 + Umwelt 15 + Gesellschaft 10)
   ================================================================ */
VOCAB: [
  /* B2-Allgemein (27) */
  /* ── Aus Nutzerliste (nicht in easy/medium) ── */
  {en:'achievement',  de:'Leistung / Errungschaft',              pron:'[əˈtʃiːvmənt]',   t:'Nomen'},
  {en:'approach',     de:'Ansatz / Methode / Herangehen',        pron:'[əˈprəʊtʃ]',      t:'Nomen'},
  {en:'circumstances',de:'Umstände / Verhältnisse',              pron:'[ˈsɜːkəmstənsɪz]',t:'Nomen'},
  {en:'development',  de:'Entwicklung / Fortschritt',            pron:'[dɪˈveləpmənt]',  t:'Nomen'},
  {en:'environment',  de:'Umwelt / Umgebung',                    pron:'[ɪnˈvaɪrənmənt]', t:'Nomen'},
  {en:'experience',   de:'Erfahrung / Erlebnis',                 pron:'[ɪkˈspɪəriəns]',  t:'Nomen'},
  {en:'government',   de:'Regierung / Staat',                    pron:'[ˈɡʌvənmənt]',    t:'Nomen'},
  /* ── Weitere B2-Allgemein ── */
  {en:'ambiguous',    de:'mehrdeutig / zweideutig',              pron:'[æmˈbɪɡjuəs]',    t:'Adjektive'},
  {en:'assertive',    de:'selbstbewusst / durchsetzungsstark',   pron:'[əˈsɜːtɪv]',      t:'Adjektive'},
  {en:'coherent',     de:'kohärent / schlüssig',                 pron:'[kəʊˈhɪərənt]',   t:'Adjektive'},
  {en:'contemplate',  de:'nachdenken über / erwägen',            pron:'[ˈkɒntəmpleɪt]',  t:'Verben'},
  {en:'contradict',   de:'widersprechen / widerlegen',           pron:'[ˌkɒntrəˈdɪkt]',  t:'Verben'},
  {en:'elaborate',    de:'ausführen / ausarbeiten / detailliert',pron:'[ɪˈlæbərət]',     t:'Verben'},
  {en:'empathy',      de:'Empathie / Einfühlungsvermögen',       pron:'[ˈempəθi]',        t:'Nomen'},
  {en:'formidable',   de:'gewaltig / beeindruckend',             pron:'[ˈfɔːmɪdəbəl]',   t:'Adjektive'},
  {en:'inevitable',   de:'unvermeidlich / unausweichlich',       pron:'[ɪnˈevɪtəbəl]',   t:'Adjektive'},
  {en:'meticulous',   de:'sorgfältig / akribisch',               pron:'[mɪˈtɪkjʊləs]',   t:'Adjektive'},
  {en:'persevere',    de:'durchhalten / beharren',               pron:'[ˌpɜːsɪˈvɪə]',    t:'Verben'},
  {en:'plausible',    de:'plausibel / glaubwürdig',              pron:'[ˈplɔːzɪbəl]',    t:'Adjektive'},
  {en:'pragmatic',    de:'pragmatisch / sachlich',               pron:'[præɡˈmætɪk]',    t:'Adjektive'},
  {en:'profound',     de:'tiefgründig / bedeutsam',              pron:'[prəˈfaʊnd]',     t:'Adjektive'},
  {en:'scrutinize',   de:'genau prüfen / untersuchen',           pron:'[ˈskruːtɪnaɪz]',  t:'Verben'},
  {en:'ambivalent',   de:'zweideutig / unentschlossen',          pron:'[æmˈbɪvələnt]',   t:'Adjektive'},
  {en:'compelling',   de:'überzeugend / fesselnd',               pron:'[kəmˈpelɪŋ]',     t:'Adjektive'},
  {en:'depict',       de:'darstellen / schildern',               pron:'[dɪˈpɪkt]',       t:'Verben'},
  {en:'discrepancy',  de:'Diskrepanz / Unstimmigkeit',           pron:'[dɪˈskrepənsi]',  t:'Nomen'},
  {en:'eloquent',     de:'redegewandt / eloquent',               pron:'[ˈeləkwənt]',     t:'Adjektive'},
  /* Technologie (15) */
  {en:'software',          de:'Software / Programm',              pron:'[ˈsɒftweər]',             t:'Technologie'},
  {en:'algorithm',         de:'Algorithmus',                      pron:'[ˈælɡərɪðəm]',            t:'Technologie'},
  {en:'encryption',        de:'Verschlüsselung',                  pron:'[ɪnˈkrɪpʃən]',            t:'Technologie'},
  {en:'bandwidth',         de:'Bandbreite',                       pron:'[ˈbændwɪdθ]',             t:'Technologie'},
  {en:'automation',        de:'Automatisierung',                  pron:'[ˌɔːtəˈmeɪʃən]',          t:'Technologie'},
  {en:'innovation',        de:'Innovation / Neuerung',            pron:'[ˌɪnəˈveɪʃən]',           t:'Technologie'},
  {en:'prototype',         de:'Prototyp / Muster',               pron:'[ˈprəʊtətaɪp]',           t:'Technologie'},
  {en:'wireless',          de:'drahtlos / kabellos',              pron:'[ˈwaɪərləs]',              t:'Technologie'},
  {en:'interface',         de:'Schnittstelle / Benutzeroberfläche',pron:'[ˈɪntəfeɪs]',            t:'Technologie'},
  {en:'cybersecurity',     de:'Cybersicherheit',                  pron:'[ˌsaɪbəsɪˈkjʊərɪti]',     t:'Technologie'},
  {en:'database',          de:'Datenbank',                        pron:'[ˈdeɪtəbeɪs]',            t:'Technologie'},
  {en:'artificial intelligence', de:'Künstliche Intelligenz',     pron:'[ˌɑːtɪˈfɪʃəl ɪnˈtelɪdʒəns]', t:'Technologie'},
  {en:'digital',           de:'digital',                          pron:'[ˈdɪdʒɪtəl]',             t:'Technologie'},
  {en:'network',           de:'Netzwerk / Netz',                  pron:'[ˈnetwɜːk]',              t:'Technologie'},
  {en:'virtual',           de:'virtuell',                         pron:'[ˈvɜːtʃuəl]',             t:'Technologie'},
  /* Umwelt (15) */
  {en:'pollution',         de:'Verschmutzung / Umweltverschmutzung', pron:'[pəˈluːʃən]',          t:'Umwelt'},
  {en:'renewable',         de:'erneuerbar',                       pron:'[rɪˈnjuːəbəl]',           t:'Umwelt'},
  {en:'sustainable',       de:'nachhaltig',                       pron:'[səˈsteɪnəbəl]',          t:'Umwelt'},
  {en:'emissions',         de:'Emissionen / Ausstoß',             pron:'[ɪˈmɪʃənz]',              t:'Umwelt'},
  {en:'ecosystem',         de:'Ökosystem',                        pron:'[ˈiːkəʊˌsɪstəm]',         t:'Umwelt'},
  {en:'biodiversity',      de:'Artenvielfalt / Biodiversität',    pron:'[ˌbaɪəʊdaɪˈvɜːsɪti]',     t:'Umwelt'},
  {en:'carbon footprint',  de:'CO₂-Fußabdruck',                  pron:'[ˈkɑːbən ˈfʊtprɪnt]',     t:'Umwelt'},
  {en:'deforestation',     de:'Abholzung / Entwaldung',           pron:'[ˌdiːˌfɒrɪˈsteɪʃən]',     t:'Umwelt'},
  {en:'conservation',      de:'Naturschutz / Erhaltung',          pron:'[ˌkɒnsəˈveɪʃən]',         t:'Umwelt'},
  {en:'greenhouse gas',    de:'Treibhausgas',                     pron:'[ˈɡriːnhaʊs ɡæs]',        t:'Umwelt'},
  {en:'endangered',        de:'gefährdet / vom Aussterben bedroht', pron:'[ɪnˈdeɪndʒəd]',         t:'Umwelt'},
  {en:'recycle',           de:'recyceln / wiederverwerten',       pron:'[ˌriːˈsaɪkəl]',           t:'Umwelt'},
  {en:'climate change',    de:'Klimawandel',                      pron:'[ˈklaɪmət tʃeɪndʒ]',      t:'Umwelt'},
  {en:'fossil fuels',      de:'fossile Brennstoffe',              pron:'[ˈfɒsəl fjuːəlz]',        t:'Umwelt'},
  {en:'contamination',     de:'Kontamination / Verseuchung',      pron:'[kənˌtæmɪˈneɪʃən]',       t:'Umwelt'},
  /* Gesellschaft (10) */
  {en:'population',        de:'Bevölkerung / Einwohnerzahl',      pron:'[ˌpɒpjʊˈleɪʃən]',         t:'Gesellschaft'},
  {en:'democracy',         de:'Demokratie',                       pron:'[dɪˈmɒkrəsi]',            t:'Gesellschaft'},
  {en:'inequality',        de:'Ungleichheit / Ungerechtigkeit',   pron:'[ˌɪnɪˈkwɒlɪti]',          t:'Gesellschaft'},
  {en:'discrimination',    de:'Diskriminierung',                  pron:'[dɪˌskrɪmɪˈneɪʃən]',      t:'Gesellschaft'},
  {en:'migration',         de:'Migration / Wanderung',            pron:'[maɪˈɡreɪʃən]',           t:'Gesellschaft'},
  {en:'legislation',       de:'Gesetzgebung',                     pron:'[ˌledʒɪˈsleɪʃən]',        t:'Gesellschaft'},
  {en:'unemployment',      de:'Arbeitslosigkeit',                 pron:'[ˌʌnɪmˈplɔɪmənt]',        t:'Gesellschaft'},
  {en:'globalisation',     de:'Globalisierung',                   pron:'[ˌɡləʊbəlaɪˈzeɪʃən]',     t:'Gesellschaft'},
  {en:'corruption',        de:'Korruption / Bestechlichkeit',     pron:'[kəˈrʌpʃən]',             t:'Gesellschaft'},
  {en:'poverty',           de:'Armut / Not',                      pron:'[ˈpɒvəti]',               t:'Gesellschaft'}
],

/* ================================================================
   PRONOUNS – 5 Reziprokpronomen
   ================================================================ */
PRONOUNS: [
  {pre:'The two friends helped',   post:'with the project.',       ans:'each other',  type:'reciprocal', de:'Die zwei Freunde halfen sich gegenseitig beim Projekt.'},
  {pre:'They looked at',           post:'in surprise.',            ans:'each other',  type:'reciprocal', de:'Sie sahen sich überrascht an.'},
  {pre:'The students taught',      post:'the new vocabulary.',     ans:'one another', type:'reciprocal', de:'Die Schüler brachten sich gegenseitig das neue Vokabular bei.'},
  {pre:'The sisters trust',        post:'completely.',             ans:'each other',  type:'reciprocal', de:'Die Schwestern vertrauen einander vollständig.'},
  {pre:'The couple supported',     post:'through difficult times.',ans:'each other',  type:'reciprocal', de:'Das Paar hat sich in schwierigen Zeiten gegenseitig unterstützt.'}
],

/* ================================================================
   GRAMMAR_QS – 18 Fragen (B2: Conditionals, Passive, Rel. Clauses, Rep. Speech)
   ================================================================ */
GRAMMAR_QS: [
  /* Third Conditional & Inversion */
  {sub:'tenses',
   q:'Third Conditional:\n"___ harder, she would have passed."',
   opts:['Had she studied','If she studied','If she had studied','She had studied'],
   ans:0,
   rule:"Inversion im Third Conditional: 'Had she studied' statt 'If she had studied'. Sehr formal."},
  {sub:'tenses',
   q:'Mixed Conditional:\n"If she had taken the job, she ___ rich now."',
   opts:['would be','would have been','will be','was'],
   ans:0,
   rule:"Mixed Conditional: If + Past Perfect (vergangene Bedingung) → would + Infinitiv (Gegenwartsergebnis)."},
  /* Future Perfect & Past Perfect Continuous */
  {sub:'tenses',
   q:'Future Perfect:\n"By next year, she ___ here for ten years."',
   opts:['will have worked','will work','has worked','would have worked'],
   ans:0,
   rule:"Future Perfect: will have + Past Participle. Für Handlungen, die bis zu einem Zeitpunkt in der Zukunft abgeschlossen sind."},
  {sub:'tenses',
   q:'Past Perfect Continuous:\n"He was exhausted because he ___ all day."',
   opts:['had been working','was working','had worked','worked'],
   ans:0,
   rule:"Past Perfect Continuous: had been + Verb-ing. Für Handlungen, die vor einem vergangenen Zeitpunkt andauerten."},
  /* Passiv – verschiedene Zeiten */
  {sub:'satzbau',
   q:'Passive – Present Perfect:\n"Someone has stolen my bike." →',
   opts:['My bike has been stolen.','My bike was stolen.','My bike is stolen.','My bike has stolen.'],
   ans:0,
   rule:"Passive Present Perfect: has/have + been + Past Participle."},
  {sub:'satzbau',
   q:'Passive – Future:\n"They will announce the results tomorrow." →',
   opts:['The results will be announced tomorrow.','The results will announce tomorrow.','The results are announced tomorrow.','The results were announced tomorrow.'],
   ans:0,
   rule:"Passive Future: will be + Past Participle. 'The results will be announced.'"},
  {sub:'tobe',
   q:'Passiv mit "to be":\n"She ___ promoted to manager last year."',
   opts:['was','were','is','has'],
   ans:0,
   rule:"Passive Simple Past: was + Past Participle. 'She was promoted.' (Singular → was)"},
  /* Relativsätze */
  {sub:'satzbau',
   q:'Relativsatz (non-defining):\n"My brother, ___ lives in Berlin, is a teacher."',
   opts:['who','that','which','whose'],
   ans:0,
   rule:"Non-defining relative clauses: IMMER 'who' für Personen, NIE 'that'. Kommas einschließen!"},
  {sub:'satzbau',
   q:'Relativsatz (defining):\n"The book ___ I borrowed is on the table."',
   opts:['that','who','whom','whose'],
   ans:0,
   rule:"Defining relative clauses für Sachen: 'that' oder 'which'. 'Who' nur für Personen."},
  {sub:'satzbau',
   q:'Possessiver Relativsatz:\n"The woman ___ car was stolen reported it to the police."',
   opts:['whose','who','that','which'],
   ans:0,
   rule:"'whose' = wessen – zeigt Besitz an. 'The woman whose car...' (ihr Auto = the woman's car)."},
  /* Reported Speech */
  {sub:'satzbau',
   q:'Reported Speech (Frage):\n"She asked: \'Where do you live?\'" →\nShe asked me where ___.',
   opts:['I lived','did I live','I live','do I live'],
   ans:0,
   rule:"Reported Questions: Keine Fragewortstellung! She asked where I lived. (Backshift: live → lived)"},
  {sub:'satzbau',
   q:'Reported Speech (Befehl):\n"He said: \'Please sit down.\'" →',
   opts:['He asked me to sit down.','He said me to sit down.','He told me sit down.','He said to sit down.'],
   ans:0,
   rule:"Reported Command: ask/tell + Objekt + to + Infinitiv. 'He asked me to sit down.'"},
  {sub:'satzbau',
   q:'Reported Speech:\n"She said: \'I am tired.\'" → She said that she ___.',
   opts:['was tired','is tired','were tired','has been tired'],
   ans:0,
   rule:"Reported Speech: Präsens → Präteritum ('is' → 'was'). Backshift nennt man das."},
  /* Gerundium & Infinitiv */
  {sub:'satzbau',
   q:'Gerundium als Subjekt:\n"___ a foreign language takes a lot of patience."',
   opts:['Learning','To learn','Learn','Learned'],
   ans:0,
   rule:"Gerundium kann als Subjekt verwendet werden: 'Learning a language...' (häufiger als Infinitiv)."},
  /* Kurzantworten */
  {sub:'short',
   q:'Richtige Kurzantwort:\n"Have you ever been to London?" – "Yes, ___"',
   opts:['I have.','I did.','I was.','I am.'],
   ans:0,
   rule:"Kurzantwort Present Perfect: Yes, I have. / No, I haven't."},
  {sub:'short',
   q:'Richtige Kurzantwort:\n"Will she come to the party?" – "No, ___"',
   opts:["she won't.",'she will not.',"she doesn't.",'she isn\'t.'],
   ans:0,
   rule:"Kurzantwort Future: No, she won't. (Kurzform von 'will not')."},
  /* To be – Passiv-Erweiterungen */
  {sub:'tobe',
   q:'Ergänze: "The report ___ finished by the end of the week."',
   opts:['must be','must is','should is','has be'],
   ans:0,
   rule:"Modal + Passiv: Modal + be + Past Participle. 'must be finished' (nie 'must is')."},
  {sub:'tenses',
   q:'Ergänze das richtige Modal:\n"She ___ have left earlier – the traffic was terrible."',
   opts:['should','must','would','could to'],
   ans:0,
   rule:"'should have + PP' = hätte + Partizip (Vorwurf / Ratschlag rückblickend). 'Could to' ist falsch."}
],

/* ================================================================
   EXAM_QS – 16 Prüfungsfragen (B2)
   ================================================================ */
EXAM_QS: [
  {sub:'home',
   q:'Wohnort auf B2-Niveau:\n"The area ___ known for its excellent transport links."',
   opts:['is','are','has','was'],
   ans:0,
   rule:"'The area' ist singular → 'is known'. Passive Konstruktion: is known for."},
  {sub:'directions',
   q:'Formelle Wegbeschreibung:\n"You ___ turn left at the traffic lights."',
   opts:['should','have','must to','are must'],
   ans:0,
   rule:"'Should' drückt eine Empfehlung aus – höflicher als 'must'. 'Must to' existiert nicht."},
  {sub:'intro',
   q:'"One of my main strengths ___ that I work well in a team."',
   opts:['is','are','was','has'],
   ans:0,
   rule:"'One of my strengths' ist ein Singular-Subjekt → 'is'. Nicht 'are' (trotz Plural 'strengths')."},
  {sub:'intro',
   q:'Fähigkeit auf B2-Niveau:\n"I ___ speak three languages fluently."',
   opts:['am able to','can to','am able','have to'],
   ans:0,
   rule:"'am able to' ist formeller als 'can'. 'Can to' ist falsch – kein 'to' nach Modalverben."},
  {sub:'family',
   q:'Veränderungen beschreiben:\n"My hometown ___ a lot since I was a child."',
   opts:['has changed','changed','is changed','was changed'],
   ans:0,
   rule:"Present Perfect für Veränderungen mit Bezug zur Gegenwart: has changed. Nicht Simple Past."},
  {sub:'home',
   q:'Nachteil beschreiben:\n"One disadvantage of living in the city centre ___ the noise."',
   opts:['is','are','has','have'],
   ans:0,
   rule:"'One disadvantage' ist Singular → 'is'. Grammatisch nach dem Subjekt richten."},
  {sub:'directions',
   q:'Indirekte Frage:\n"Could you tell me ___ the nearest pharmacy is?"',
   opts:['where','that where','what','which'],
   ans:0,
   rule:"Indirekte Frage: Could you tell me where... (Fragewort leitet Nebensatz in normaler Satzstellung ein)."},
  {sub:'family',
   q:'Superlativ auf B2:\n"She is the ___ person I have ever met."',
   opts:['most generous','more generous','generousest','most generously'],
   ans:0,
   rule:"Superlativ mehrsilbiger Adjektive: the most + Adjektiv. Nie -est bei mehrsilbigen Wörtern."},
  {sub:'intro',
   q:'Ergänze das Passiv:\n"The decision ___ by the whole committee."',
   opts:['was made','made','has make','is making'],
   ans:0,
   rule:"Passive Simple Past: was/were + Past Participle. 'The decision was made by...'"},
  {sub:'home',
   q:'Beschreibe Veränderungen:\n"A new park ___ in our neighbourhood."',
   opts:['has been built','has built','was building','builds'],
   ans:0,
   rule:"Passive Present Perfect: has/have been + Past Participle. Verbindung zur Gegenwart."},
  {sub:'family',
   q:'Conditional auf B2:\n"If she ___ harder, she would have got the job."',
   opts:['had tried','tried','would try','has tried'],
   ans:0,
   rule:"Third Conditional: If + Past Perfect (had tried) → would have + Past Participle."},
  {sub:'directions',
   q:'Wegbeschreibung mit Relativsatz:\n"The museum, ___ is five minutes from here, is free on Sundays."',
   opts:['which','that','who','whose'],
   ans:0,
   rule:"Non-defining relative clause für Sachen: immer 'which', nie 'that'. Kommas nicht vergessen!"},
  {sub:'intro',
   q:'Reported Speech:\n"She said: \'I will do it tomorrow.\'" →\nShe said she ___ do it the following day.',
   opts:['would','will','was going','should'],
   ans:0,
   rule:"Backshift in Reported Speech: 'will' → 'would'. 'Tomorrow' → 'the following day'."},
  {sub:'home',
   q:'Gerundium als Subjekt:\n"___ in the city centre has its advantages and disadvantages."',
   opts:['Living','To live','Live','Lived'],
   ans:0,
   rule:"Gerundium als Satzsubjekt: 'Living in the city centre...' (häufiger als Infinitiv in dieser Position)."},
  {sub:'directions',
   q:'Formelle Alternative:\n"Go to the end of the street" =\n"Proceed ___ the end of the street."',
   opts:['to','at','until','towards'],
   ans:0,
   rule:"'Proceed to' = gehen bis zu (formell). 'Proceed towards' = sich in Richtung bewegen. 'Proceed to the end' ist idiomatisch korrekt."},
  {sub:'family',
   q:'Ergänze:\n"___ is an only child means she never had siblings to play with."',
   opts:['Being','To be','Be','Been'],
   ans:0,
   rule:"Gerundium als Satzsubjekt: 'Being an only child means...' – die -ing Form fungiert als Nomen."},

  /* ======== Geografie – Schwer (25 Fragen) ======== */
  /* Österreich – Spezialwissen */
  {sub:'geo', q:'Wie heißt der zweithöchste Berg Österreichs?',
   opts:['Wildspitze','Dachstein','Großvenediger','Similaun'], ans:0,
   rule:'Die Wildspitze in den Ötztaler Alpen ist mit 3.768 m der zweithöchste Berg Österreichs.'},
  {sub:'geo', q:'In welchem Bundesland liegt der Neusiedler See?',
   opts:['Burgenland','Niederösterreich','Steiermark','Kärnten'], ans:0,
   rule:'Der Neusiedler See liegt im Burgenland an der Grenze zu Ungarn.'},
  {sub:'geo', q:'Welcher Fluss fließt durch die Stadt Graz?',
   opts:['Mur','Drau','Enns','Inn'], ans:0,
   rule:'Die Mur fließt durch die steirische Landeshauptstadt Graz.'},
  {sub:'geo', q:'Ergänze: "Die Hauptstadt von Liechtenstein ist ___."',
   opts:['Vaduz','Schaan','Feldkirch','Bregenz'], ans:0,
   rule:'Vaduz ist die Hauptstadt des Fürstentums Liechtenstein, des kleinsten Nachbarlandes Österreichs.'},
  {sub:'geo', q:'An welchem See liegt die Stadt Bregenz?',
   opts:['Bodensee','Neusiedler See','Attersee','Traunsee'], ans:0,
   rule:'Bregenz, die Hauptstadt Vorarlbergs, liegt am Bodensee.'},
  {sub:'geo', q:'Welcher Fluss fließt durch die Stadt Innsbruck?',
   opts:['Inn','Salzach','Mur','Enns'], ans:0,
   rule:'Der Inn fließt durch Innsbruck – der Name der Stadt leitet sich davon ab (Brücke über den Inn).'},
  {sub:'geo', q:'Welcher ist der größte See, der vollständig in Österreich liegt?',
   opts:['Attersee','Wörthersee','Traunsee','Bodensee'], ans:0,
   rule:'Der Attersee im Salzkammergut ist der größte See, der vollständig in Österreich liegt.'},
  {sub:'geo', q:'Welcher Fluss fließt durch Kärnten und Osttirol?',
   opts:['Drau','Mur','Inn','Salzach'], ans:0,
   rule:'Die Drau fließt durch Osttirol und Kärnten und ist einer der wichtigsten Flüsse Südösterreichs.'},
  {sub:'geo', q:'Ergänze: "Der Fluss ___ bildet historisch die Grenze zwischen Ober- und Niederösterreich."',
   opts:['Enns','Traun','Inn','Salzach'], ans:0,
   rule:'Die Enns bildete historisch die Grenze zwischen Ober- und Niederösterreich (daher die Namen).'},
  {sub:'geo', q:'In welchem Bundesland liegt der Wörthersee?',
   opts:['Kärnten','Steiermark','Salzburg','Tirol'], ans:0,
   rule:'Der Wörthersee liegt in Kärnten bei Klagenfurt und ist einer der wärmsten Alpenseen.'},

  /* Europa – Fortgeschritten */
  {sub:'geo', q:'Wie heißt die Hauptstadt von Norwegen?',
   opts:['Oslo','Stockholm','Helsinki','Kopenhagen'], ans:0,
   rule:'Oslo ist die Hauptstadt und größte Stadt Norwegens.'},
  {sub:'geo', q:'Ergänze: "Die Hauptstadt von Schweden ist ___."',
   opts:['Stockholm','Oslo','Helsinki','Kopenhagen'], ans:0,
   rule:'Stockholm ist die Hauptstadt und größte Stadt Schwedens.'},
  {sub:'geo', q:'Durch wie viele Länder fließt die Donau?',
   opts:['10','6','8','12'], ans:0,
   rule:'Die Donau fließt durch 10 Länder – mehr als jeder andere Fluss der Welt.'},
  {sub:'geo', q:'Welcher Fluss fließt durch Paris?',
   opts:['Seine','Rhein','Loire','Themse'], ans:0,
   rule:'Die Seine fließt durch die französische Hauptstadt Paris.'},
  {sub:'geo', q:'Welches Meer liegt zwischen Südosteuropa und Kleinasien?',
   opts:['Schwarzes Meer','Mittelmeer','Nordsee','Ostsee'], ans:0,
   rule:'Das Schwarze Meer liegt zwischen Südosteuropa und Kleinasien (Türkei).'},
  {sub:'geo', q:'Wie heißt die Hauptstadt der Niederlande?',
   opts:['Amsterdam','Den Haag','Rotterdam','Utrecht'], ans:0,
   rule:'Amsterdam ist die offizielle Hauptstadt der Niederlande (der Regierungssitz ist Den Haag).'},

  /* England / London – Fortgeschritten */
  {sub:'geo', q:'Wie heißt die berühmte Abtei in London, in der Könige gekrönt werden?',
   opts:['Westminster Abbey','Canterbury Cathedral','St. Paul\'s Cathedral','York Minster'], ans:0,
   rule:'In der Westminster Abbey werden die britischen Monarchen traditionell gekrönt.'},
  {sub:'geo', q:'Wie heißt der große Park im Zentrum Londons?',
   opts:['Hyde Park','Central Park','Green Park','Regent\'s Park'], ans:0,
   rule:'Der Hyde Park ist einer der größten und bekanntesten Parks im Zentrum von London.'},
  {sub:'geo', q:'Wer ist das Staatsoberhaupt des Vereinigten Königreichs?',
   opts:['Der König / Die Königin','Der Premierminister','Der Präsident','Der Kanzler'], ans:0,
   rule:'Das Vereinigte Königreich ist eine konstitutionelle Monarchie – das Staatsoberhaupt ist der König oder die Königin.'},

  /* New York – Fortgeschritten */
  {sub:'geo', q:'In welchem US-Bundesstaat liegt New York City?',
   opts:['New York','New Jersey','Connecticut','Pennsylvania'], ans:0,
   rule:'New York City liegt im gleichnamigen US-Bundesstaat New York.'},
  {sub:'geo', q:'Wie heißt das berühmte Hochhaus in New York, das 1931 eröffnet wurde?',
   opts:['Empire State Building','One World Trade Center','Chrysler Building','Freedom Tower'], ans:0,
   rule:'Das Empire State Building wurde 1931 eröffnet und war lange das höchste Gebäude der Welt.'},
  {sub:'geo', q:'Wie heißt die berühmte Brücke, die Manhattan mit Brooklyn verbindet?',
   opts:['Brooklyn Bridge','Manhattan Bridge','George Washington Bridge','Williamsburg Bridge'], ans:0,
   rule:'Die Brooklyn Bridge wurde 1883 eröffnet und verbindet Manhattan mit Brooklyn über den East River.'},

  /* Australien – Fortgeschritten */
  {sub:'geo', q:'Wie heißt das trockene Landesinnere Australiens?',
   opts:['Outback','Bush','Wildnis','Savanne'], ans:0,
   rule:'Das Outback bezeichnet das trockene, dünn besiedelte Landesinnere Australiens.'},
  {sub:'geo', q:'Wie heißt die berühmte Brücke im Hafen von Sydney?',
   opts:['Harbour Bridge','Sydney Bridge','Port Bridge','Opera Bridge'], ans:0,
   rule:'Die Sydney Harbour Bridge ist eine der bekanntesten Brücken der Welt.'},
  {sub:'geo', q:'Welches besondere australische Tier legt Eier und hat einen Schnabel?',
   opts:['Schnabeltier','Koala','Känguru','Wombat'], ans:0,
   rule:'Das Schnabeltier (Platypus) ist eines der wenigen Säugetiere, die Eier legen.'},

  /* ── Österreich – Flüsse & Seen (Fortgeschritten) ── */
  {sub:'geo', q:'Welcher Fluss fließt durch die steirische Landeshauptstadt Graz und mündet in die Drau?',
   opts:['Mur','Enns','Raab','Salzach'], ans:0,
   rule:'Die Mur fließt durch Graz und mündet in Kroatien in die Drau.'},
  {sub:'geo', q:'Welches ist das flächenmäßig kleinste Bundesland Österreichs?',
   opts:['Wien','Vorarlberg','Burgenland','Salzburg'], ans:0,
   rule:'Wien ist mit 415 km² das kleinste Bundesland Österreichs.'},
  {sub:'geo', q:'Wie viele Nachbarländer hat Österreich?',
   opts:['8','6','7','9'], ans:0,
   rule:'Österreich hat 8 Nachbarländer: D, CH, LI, IT, SLO, HU, SK, CZ.'},
  {sub:'geo', q:'Welcher See in Kärnten ist der wärmste Badesee der Alpen?',
   opts:['Klopeiner See','Wörthersee','Millstätter See','Ossiacher See'], ans:0,
   rule:'Der Klopeiner See in Kärnten gilt als wärmster Badesee der Alpen.'},
  {sub:'geo', q:'Ergänze: "Der Enns-Fluss bildet die historische Grenze zwischen ___ und ___."',
   opts:['Ober- und Niederösterreich','Tirol und Salzburg','Steiermark und Kärnten','Wien und Burgenland'], ans:0,
   rule:'Die Enns trennte historisch "ob der Enns" (Oberösterreich) von "unter der Enns" (Niederösterreich).'},

  /* ── Europa – Fortgeschritten ── */
  {sub:'geo', q:'Welcher ist der längste Fluss Europas?',
   opts:['Wolga','Donau','Rhein','Dnjepr'], ans:0,
   rule:'Die Wolga in Russland ist mit ca. 3.530 km der längste Fluss Europas.'},
  {sub:'geo', q:'Welches ist der kleinste unabhängige Staat der Welt?',
   opts:['Vatikanstadt','Monaco','San Marino','Liechtenstein'], ans:0,
   rule:'Die Vatikanstadt hat nur 0,44 km² und ist der kleinste anerkannte Staat der Welt.'},
  {sub:'geo', q:'Welches Gebirge bildet die traditionelle Grenze zwischen Europa und Asien?',
   opts:['Ural','Kaukasus','Karpaten','Alpen'], ans:0,
   rule:'Der Ural in Russland gilt als traditionelle Grenze zwischen Europa und Asien.'},
  {sub:'geo', q:'Welches ist die größte Mittelmeer-Insel?',
   opts:['Sizilien','Sardinien','Korsika','Kreta'], ans:0,
   rule:'Sizilien (Italien) ist mit ca. 25.400 km² die größte Insel im Mittelmeer.'},
  {sub:'geo', q:'Wie heißt die Meerenge zwischen Europa und Asien bei Istanbul?',
   opts:['Bosporus','Dardanellen','Straße von Gibraltar','Straße von Messina'], ans:0,
   rule:'Der Bosporus trennt den europäischen vom asiatischen Teil Istanbuls.'},

  /* ── London – Fortgeschritten ── */
  {sub:'geo', q:'Wie heißt die berühmte Kathedrale in London, in der Königskrönungen stattfinden?',
   opts:['Westminster Abbey','St Paul\'s Cathedral','Canterbury Cathedral','Tower Chapel'], ans:0,
   rule:'Westminster Abbey ist die Krönungskirche der britischen Monarchen seit 1066.'},
  {sub:'geo', q:'In welcher Zeitzone liegt London?',
   opts:['GMT / UTC+0','CET / UTC+1','EST / UTC-5','PST / UTC-8'], ans:0,
   rule:'London liegt in der Greenwich Mean Time (GMT), also UTC+0.'},
  {sub:'geo', q:'Wie heißt das Riesenrad an der Themse in London?',
   opts:['London Eye','Big Wheel','Thames Wheel','Sky Wheel'], ans:0,
   rule:'Das London Eye ist eines der größten Riesenräder der Welt am Südufer der Themse.'},

  /* ── New York – Fortgeschritten ── */
  {sub:'geo', q:'Aus wie vielen Stadtbezirken (Boroughs) besteht New York City?',
   opts:['5','4','6','3'], ans:0,
   rule:'NYC hat 5 Boroughs: Manhattan, Brooklyn, Queens, Bronx und Staten Island.'},
  {sub:'geo', q:'An welchem Fluss liegt Manhattan auf der Westseite?',
   opts:['Hudson River','East River','Delaware River','Harlem River'], ans:0,
   rule:'Der Hudson River fließt westlich von Manhattan und mündet in den Atlantik.'},
  {sub:'geo', q:'Wie heißt der große Park im Herzen von Manhattan?',
   opts:['Central Park','Hyde Park','Prospect Park','Battery Park'], ans:0,
   rule:'Der Central Park ist eine 3,4 km² große Grünfläche mitten in Manhattan.'},

  /* ── Australien – Fortgeschritten ── */
  {sub:'geo', q:'In welchem australischen Bundesstaat/Territorium liegt der Uluru?',
   opts:['Northern Territory','South Australia','Western Australia','Queensland'], ans:0,
   rule:'Der Uluru liegt im Northern Territory, im roten Zentrum Australiens.'},
  {sub:'geo', q:'Welches Riff vor der Küste Australiens ist das größte Korallenriff der Welt?',
   opts:['Great Barrier Reef','Ningaloo Reef','Lord Howe Reef','Coral Sea Reef'], ans:0,
   rule:'Das Great Barrier Reef vor Queensland ist mit über 2.300 km das größte Korallenriff der Welt.'},
  {sub:'geo', q:'Wie heißt die Hauptstadt Australiens?',
   opts:['Canberra','Sydney','Melbourne','Brisbane'], ans:0,
   rule:'Canberra ist die Hauptstadt Australiens, nicht Sydney oder Melbourne.'}
]

}; // END DATA_HARD
